compile.sh: use bash instead of sh
The emscripten tools are expecting bash or more, and will fail at
runtime if ran with sh.

    Setting the environment
    Error: unable to determine 'emsdk' directory. Perhaps you are using a shell or
           environment that this script does not support.